# -*- coding: utf-8 -*-
"""dummy-llama32-3B-responsegen-finetuning.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Jf5Uc6VCzlxxwOcGQiDD97vbVwgC9-1A

# ResponsGen Fine-Tuning

Fine-tuning Llama 3.2 3B on the MLP4CS RResponseGen dataset using Unsloth + (Q)LoRA.

Task: given conversation history + domain + intent + slots → generate delexicalized system response.

## Installation
"""

# Commented out IPython magic to ensure Python compatibility.
# %%capture
# import os, re
# if "COLAB_" not in "".join(os.environ.keys()):
#     !pip install unsloth
# else:
#     import torch; v = re.match(r'[\d]{1,}\.[\d]{1,}', str(torch.__version__)).group(0)
#     xformers = 'xformers==' + {'2.10':'0.0.34','2.9':'0.0.33.post1','2.8':'0.0.32.post2'}.get(v, "0.0.34")
#     !pip install sentencepiece protobuf "datasets==4.3.0" "huggingface_hub>=0.34.0" hf_transfer
#     !pip install --no-deps unsloth_zoo bitsandbytes accelerate {xformers} peft trl triton unsloth
# !pip install transformers==4.56.2
# !pip install --no-deps trl==0.22.2

"""## Unsloth Model & (Q)LoRA"""

from unsloth import FastLanguageModel
import torch
max_seq_length = 2048
dtype = None
load_in_4bit = True
# if True: QLoRA with base model in 4-bit, adapters in 16-bit (needs ~3GB VRAM)
# if False: LoRA with a base model in 16-bit (needs ~6GB VRAM)

model, tokenizer = FastLanguageModel.from_pretrained(
    model_name = "ilsp/Llama-Krikri-8B-Instruct",
    max_seq_length = max_seq_length,
    dtype = dtype,
    load_in_4bit = load_in_4bit,
)

model

"""We now add LoRA adapters so we only need to update 1 to 10% of all parameters!"""

model = FastLanguageModel.get_peft_model(
    model,
    r = 16,
    target_modules = ["q_proj", "k_proj", "v_proj", "o_proj", "gate_proj", "up_proj", "down_proj"],
    lora_alpha = 16,
    lora_dropout = 0,
    bias = "none",
    use_gradient_checkpointing = "unsloth",
    random_state = 3407,
    use_rslora = False,
    loftq_config = None,
)

model

"""## Test BEFORE Fine-Tuning

Run 3 examples from our dataset through the base model. We expect the model to generate generic responses as it has never seen our delexicalized format.
"""

FastLanguageModel.for_inference(model) # Ενεργοποιεί την ταχύτατη λειτουργία inference του Unsloth

# Φτιάχνουμε μια ερώτηση χρήστη (όπως αυτές που έχει το JSON σου)
messages = [
    {"role": "user", "content": "Θέλω να ανακαλύψω νέους καλλιτέχνες, έχεις κάτι που είναι λίγο έντονο ή δραματικό;"}
]

# Χρησιμοποιούμε το template που ορίσαμε νωρίτερα
inputs = tokenizer.apply_chat_template(
    messages,
    tokenize = True,
    add_generation_prompt = True, # Λέει στο μοντέλο ότι τώρα είναι η σειρά του assistant να μιλήσει
    return_tensors = "pt",
).to("cuda")

# Βάζουμε το μοντέλο να παράγει απάντηση (μέχρι 128 tokens για αρχή)
outputs = model.generate(input_ids = inputs, max_new_tokens = 128, use_cache = True)
print(tokenizer.batch_decode(outputs)[0])

# Pick 3 examples to test
test_examples = all_examples[:3]
test_examples

def run_inference(model, tokenizer, example):
    messages = [
        {"role": "user", "content": f"{example['instruction']}\n\n{example['input']}"}
    ]
    inputs = tokenizer.apply_chat_template(
        messages,
        tokenize = True,
        add_generation_prompt = True,
        return_tensors = "pt",
    ).to("cuda")

    outputs = model.generate(input_ids=inputs, max_new_tokens=128, use_cache=True, do_sample=False)
    decoded = tokenizer.batch_decode(outputs, skip_special_tokens=True)[0]
    return decoded.split("assistant")[-1].strip()

FastLanguageModel.for_inference(model)

print("=" * 60)
print("RESULTS BEFORE FINE-TUNING")
print("=" * 60)
for i, ex in enumerate(test_examples):
    pred = run_inference(model, tokenizer, ex)
    print(f"\n>>> Example {i+1} (turn {ex['turn_id']})")
    print(f"\nINPUT:\n{ex['input']}")
    print(f"\nEXPECTED:\n{ex['output']}")
    print(f"\nPREDICTION:\n{pred}")

"""## Data Preparation

Format our JSON into Alpaca-style text: `### Instruction / ### Input / ### Response`.
"""

from datasets import load_dataset
from unsloth.chat_templates import get_chat_template

# 1. Φορτώνουμε το template διαλόγου του Llama-3
tokenizer = get_chat_template(
    tokenizer,
    chat_template = "llama-3",
    mapping = {"role" : "role", "content" : "content", "user" : "user", "assistant" : "assistant"}
)

# 2. Συνάρτηση που μετατρέπει τους διαλόγους στο σωστό text format
def format_chat(examples):
    texts = [tokenizer.apply_chat_template(convo, tokenize=False, add_generation_prompt=False) for convo in examples["conversations"]]
    return {"text": texts}

# 3. Φορτώνουμε το αρχείο μας από το Google Drive
# ΠΡΟΣΟΧΗ: Αν το αρχείο σου είναι σε άλλο φάκελο στο Drive, άλλαξε το path!
data_path = "unsloth_dataset.json"

dataset = load_dataset("json", data_files={"train": data_path}, split="train")

# 4. Εφαρμόζουμε την αλλαγή σε όλο το dataset
dataset = dataset.map(format_chat, batched=True)

print(f"Loaded {len(dataset)} conversational examples successfully!")

dataset

print("Sample formatted text (first example):")
print(dataset[0]["text"])

"""## Train"""

# GPU memory before training
gpu_stats = torch.cuda.get_device_properties(0)
start_gpu_memory = round(torch.cuda.max_memory_reserved() / 1024 / 1024 / 1024, 3)
max_memory = round(gpu_stats.total_memory / 1024 / 1024 / 1024, 3)
print(f"GPU = {gpu_stats.name}. Max memory = {max_memory} GB.")
print(f"{start_gpu_memory} GB of memory reserved before training.")

optim = "adamw_8bit" if load_in_4bit else "adamw_torch"
print(f"Using {optim} optimizer.")

FastLanguageModel.for_training(model)
from trl import SFTConfig, SFTTrainer
trainer = SFTTrainer(
    model = model,
    tokenizer = tokenizer,
    train_dataset = dataset,
    dataset_text_field = "text",
    max_seq_length = max_seq_length,
    packing = False,
    args = SFTConfig(
        per_device_train_batch_size = 2,
        gradient_accumulation_steps = 4,
        warmup_steps = 10,
        num_train_epochs = 1,
        # max_steps = 60,
        # num_train_epochs = 1,  # full training: sees all 11,686 examples, e.g., for 3 epochs × 3 times (~4hrs on T4)
        # max_steps = 60,  # quick test: stops after 60 steps regardless of dataset size (~4min on T4)
        learning_rate = 2e-4,
        logging_steps = 10,
        optim = optim,
        weight_decay = 0.001,
        lr_scheduler_type = "linear",
        seed = 3407,
        output_dir = "respgen_outputs",
        report_to = "none",
    ),
)

trainer.train_dataset

# Train
trainer_stats = trainer.train()

# GPU memory after training
used_memory = round(torch.cuda.max_memory_reserved() / 1024 / 1024 / 1024, 3)
used_memory_for_lora = round(used_memory - start_gpu_memory, 3)
print(f"\n{round(trainer_stats.metrics['train_runtime']/60, 2)} minutes used for training.")
print(f"Peak reserved memory = {used_memory} GB.")
print(f"Peak reserved memory for LoRA = {used_memory_for_lora} GB.")

"""## Test AFTER Fine-Tuning

Same 3 examples as before. Compare predicted vs expected output. We expect the model to generate responses in our delexicalized format: `[restaurant_name]`, `PHONE`, etc.
"""

FastLanguageModel.for_inference(model)

print("=" * 60)
print("RESULTS AFTER FINE-TUNING")
print("=" * 60)
for i, ex in enumerate(test_examples):
    pred = run_inference(model, tokenizer, ex)
    print(f"\n>>> Example {i+1} (turn {ex['turn_id']})")
    print(f"\nINPUT:\n{ex['input']}")
    print(f"\nEXPECTED:\n{ex['output']}")
    print(f"\nPREDICTION:\n{pred}")

"""## Save LoRA adapter"""

# Save locally
model.save_pretrained("respgen_lora")
tokenizer.save_pretrained("respgen_lora")

# Zip into Kaggle's output folder
import shutil
shutil.make_archive("/kaggle/working/respgen_lora", "zip", "respgen_lora")

